services:
  memcached:
    image: memcached:1.6.38-alpine
    hostname: memcached-rinha
    ports: 
      - "11211:11211"
    networks:
      - application-internal
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "50MB"

  nginx:
    image: nginx:1.29.0-alpine
    hostname: nginx-rinha
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    depends_on:
      - application-node-1
      - application-node-2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 20s
    networks:
      - application-internal
      - application-external
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "60MB"

  database:
    image: postgres:17.5-alpine
    hostname: database-rinha
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - application-internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rinha-enferrujada -d rinha-enferrujada"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s 
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "165MB"

  application-node-1: &application-node-1
    build: 
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
    hostname: application-node-1
    container_name: application-node-1
    env_file: .env
    environment:
      - PORT=8080
      - COST=1
    networks:
      - application-internal
    depends_on:
      database:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "30MB" 
  
  application-node-2:
    <<: *application-node-1
    hostname: application-node-2
    container_name: application-node-2
    environment:
      - PORT=8081
      - COST=2

  migrations:
    build:
      context: Dockerfile.migrations
      args:
        - DATABASE_URL=${DATABASE_URL}
    hostname: migrations
    container_name: migrations
    env_file: .env
    networks:
      - application-internal
    depends_on:
      database:
        condition: service_healthy
    command: ["sh", "-c", "diesel setup && diesel migration run"]
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "30MB"
    restart: on-failure

networks:
  application-internal:
    driver: bridge
  application-external:
    driver: bridge

